# Generated by Django 3.2.8 on 2021-10-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=50)),
                ('fecha_de_nacimiento', models.DateField()),
                ('dni', models.FloatField(help_text='ingresar el nro de corrido y sin puntos', max_length=8)),
                ('telefono', models.FloatField(help_text='ingresar el nro sin 0 ni 15', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('idiomas', models.CharField(choices=[('ingles', 'ingles'), ('frances', 'francés'), ('italiano', 'italiano'), ('otros', 'otros (especifique)')], default='ingles', max_length=25)),
            ],
        ),
    ]
