# Generated by Django 3.2.8 on 2021-10-20 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='edad',
            field=models.FloatField(default=0, max_length=2),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='foto',
            field=models.ImageField(default=2, upload_to=None),
            preserve_default=False,
        ),
    ]
