# Generated by Django 3.2.8 on 2021-10-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20211020_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='edad',
            field=models.IntegerField(default=0),
        ),
    ]
