# Generated by Django 3.2.8 on 2021-10-21 00:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_curriculum_edad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curriculum',
            name='otros',
        ),
        migrations.AddField(
            model_name='curriculum',
            name='carta',
            field=models.TextField(default=django.utils.timezone.now, help_text='OPCIONAL', verbose_name='Carta de presentación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='hobbies',
            field=models.TextField(blank=True, help_text='OPCIONAL. Describa actividades que realiza por fuera de su actividad laboral', verbose_name='Hobbies y tiempo libre'),
        ),
        migrations.AddField(
            model_name='idioma',
            name='comentarios',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='idioma',
            field=models.CharField(blank=True, choices=[('ingles', 'Ingles'), ('frances', 'Francés'), ('italiano', 'Italiano'), ('alemán', 'Alemán'), ('Otros (especificar)', 'Otros (especificar)')], default='ingles', max_length=25),
        ),
        migrations.CreateModel(
            name='Experiencia_Laboral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=250, verbose_name='Lugar de trabajo (Empresa,Institución, etc)')),
                ('periodo_trabajado', models.DurationField()),
                ('puesto', models.CharField(max_length=50)),
                ('descripcion', models.TextField(verbose_name='Descripcióon del puesto y tareas realizadas')),
                ('referencias', models.CharField(blank=True, help_text='Opcional. Ingresar TE de contacto sin 0 ni 15', max_length=10)),
                ('referencias2', models.CharField(blank=True, help_text='ingrese nombre y puesto de la referencia', max_length=250, verbose_name='Datos de referencia')),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.curriculum')),
            ],
        ),
        migrations.CreateModel(
            name='Estudios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('Primario', 'primario'), ('Secundario', 'Secundario'), ('Terciario', 'Terciario'), ('Universitario', 'Universitario')], default='Primario', max_length=15)),
                ('institucion', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('En curso', 'En curso'), ('Finalizado', 'Finalizado'), ('Abandonado', 'Abandonado')], default='En curso', max_length=15)),
                ('comentarios', models.CharField(blank=True, max_length=250)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.curriculum')),
            ],
        ),
    ]
