# Generated by Django 3.2.8 on 2021-10-23 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211023_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experiencia_laboral',
            old_name='descripcion',
            new_name='nombre_completo',
        ),
    ]
