# Generated by Django 3.2.8 on 2021-11-04 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_rename_descripcion_experiencia_laboral_nombre_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudios',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='estudios',
            name='fecha',
        ),
        migrations.AddField(
            model_name='estudios',
            name='carrera',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudios',
            name='fecha_de_inicio_estudio',
            field=models.DateField(default=django.utils.timezone.now, help_text='En caso que esté en curso, la fecha puede ser estimativa', verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='estudios',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='blog.curriculum'),
        ),
        migrations.AlterField(
            model_name='idioma',
            name='comentarios',
            field=models.TextField(blank=True, help_text='Opcional'),
        ),
    ]
