# Generated by Django 3.2.8 on 2021-11-06 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20211104_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idioma',
            new_name='Conocimientos_Adicionales',
        ),
    ]
