# Generated by Django 3.2.8 on 2021-11-06 23:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_rename_idioma_conocimientos_adicionales'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='domicilio',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curriculum',
            name='localidad',
            field=models.CharField(default=django.utils.timezone.now, help_text='Ingrese provincia y localidad', max_length=250),
            preserve_default=False,
        ),
    ]
