# Generated by Django 3.2.8 on 2021-11-06 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20211106_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conocimientos_adicionales',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conocimientos', to='blog.curriculum'),
        ),
        migrations.AlterField(
            model_name='experiencia_laboral',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiencia', to='blog.curriculum'),
        ),
        migrations.CreateModel(
            name='Redes_Sociales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=50)),
                ('twitter', models.CharField(blank=True, max_length=50)),
                ('instagram', models.CharField(blank=True, max_length=50)),
                ('linkedin', models.CharField(blank=True, max_length=50)),
                ('otros', models.CharField(blank=True, max_length=50)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redes', to='blog.curriculum')),
            ],
        ),
    ]
