# Generated by Django 3.2.8 on 2021-11-07 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20211106_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redes_sociales',
            name='otros',
            field=models.CharField(blank=True, help_text='especifica red y usuario', max_length=50),
        ),
    ]
