# Generated by Django 3.2.8 on 2021-11-07 01:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_redes_sociales_otros'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculum',
            name='nacionalidad',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
